In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
inventory_excel = pd.read_excel(
    "10.1.25-7.31.26 OP Final.xlsx",
    sheet_name="sales-master",
    header=2
)

inventory_excel.head()

,Order Number,Sale Date,Order Status,Fulfillment Status,Wine Club Name,Cashier,Order Source,Shipping Method,Customer No.,Pickup,...,Bill Last Name,Bill State,Bill Zip,Bill Email,Bill Phone,Ship Phone,Product Title,Part No,Qty,Net Revenue
0,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle fee,0003,-1,-1.40
1,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle processing fee,0004,-1,-0.12
2,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2023 Audacious,AUD23,-4,-234.00
3,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2022 Sagacious,SAG22,-4,-234.00
4,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2025 Rosé,ROSE25,-3,-81.90

In [5]:
print(inventory_excel.shape)

print("\nDate range:")
print(inventory_excel["Sale Date"].min())
print(inventory_excel["Sale Date"].max())

print("\nOrder Sources:")
print(inventory_excel["Order Source"].value_counts())

print("\nSample Products:")
print(inventory_excel["Product Title"].dropna().unique()[:20])

(38598, 21)

Date range:
2025-10-08 11:52:32.463000
2026-07-31 21:14:43.700000

Order Sources:
Order Source
Point of Sale    22792
Wine Club         8550
Admin Cart        6967
Web Store          288
Name: count, dtype: int64

Sample Products:
['CA bottle fee' 'CA bottle processing fee' '2023 Audacious' '2022 Sagacious'
 '2025 Rosé' '2024 SOPH' '2022 Audacious'
 'Black Label Dinner Ticket Feb 28th, 2026' '2022 Beguiling' '2022 Aspire'
 'NEW GUEST $0' 'NO SHOW FEE' '2023 Rosé' 'RETURN MEMBER $0' '2021 The Nines'
 'NEW MEMBER $0' 'WhiteLabelMembershipWaitlist' '2023 SOPH'
 'RETURN INDUSTRY $0' 'NEW GUEST $50']

In [6]:
inventory_excel.to_csv("Inventory.csv", index=False)

In [7]:
inventory = pd.read_csv("Inventory.csv")

print(inventory.shape)
inventory.head()

(38598, 21)

<positron-console-cell-7>:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.

,Order Number,Sale Date,Order Status,Fulfillment Status,Wine Club Name,Cashier,Order Source,Shipping Method,Customer No.,Pickup,...,Bill Last Name,Bill State,Bill Zip,Bill Email,Bill Phone,Ship Phone,Product Title,Part No,Qty,Net Revenue
0,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle fee,0003,-1,-1.40
1,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle processing fee,0004,-1,-0.12
2,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2023 Audacious,AUD23,-4,-234.00
3,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2022 Sagacious,SAG22,-4,-234.00
4,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2025 Rosé,ROSE25,-3,-81.90

In [8]:
print("Columns:")
print(inventory.columns.tolist())

print("\nData Types:")
print(inventory.dtypes)

print("\nMissing Values:")
print(inventory.isna().sum())

print("\nDuplicate Rows:")
print(inventory.duplicated().sum())

Columns:
['Order Number', 'Sale Date', 'Order Status', 'Fulfillment Status', 'Wine Club Name', 'Cashier', 'Order Source', 'Shipping Method', 'Customer No.', 'Pickup', 'Bill First Name', 'Bill Last Name', 'Bill State', 'Bill Zip', 'Bill Email', 'Bill Phone', 'Ship Phone', 'Product Title', 'Part No', 'Qty', 'Net Revenue']

Data Types:
Order Number          float64
Sale Date              object
Order Status           object
Fulfillment Status     object
Wine Club Name         object
Cashier                object
Order Source           object
Shipping Method        object
Customer No.          float64
Pickup                 object
Bill First Name        object
Bill Last Name         object
Bill State             object
Bill Zip               object
Bill Email             object
Bill Phone             object
Ship Phone             object
Product Title          object
Part No                object
Qty                     int64
Net Revenue           float64
dtype: object

Missing Values:
Order Number              1
Sale Date                 1
Order Status             17
Fulfillment Status    11278
Wine Club Name        30038
Cashier                   1
Order Source              1
Shipping Method           1
Customer No.              1
Pickup                    1
Bill First Name          28
Bill Last Name            4
Bill State             9769
Bill Zip               9393
Bill Email              531
Bill Phone             3150
Ship Phone                1
Product Title             1
Part No                   1
Qty                       0
Net Revenue               0
dtype: int64

Duplicate Rows:
0

In [9]:
inventory.describe(include="all")

,Order Number,Sale Date,Order Status,Fulfillment Status,Wine Club Name,Cashier,Order Source,Shipping Method,Customer No.,Pickup,...,Bill Last Name,Bill State,Bill Zip,Bill Email,Bill Phone,Ship Phone,Product Title,Part No,Qty,Net Revenue
count,38597.000000,38597,38581,27320,8560,38597,38597,38597,38597.000000,38597,...,38594,28829,29205,38067,35448,38597,38597,38597,38598.000000,3.859800e+04
unique,NaN,9560,5,3,14,23,4,6,NaN,2,...,4360,54,1766,5592,5132,2322,156,156,NaN,NaN
top,NaN,2026-03-07 11:43:43.510,Released,Released,"Black Label (12 btls Fall, 3 btls Spring)",Oliver Esparham,Point of Sale,Pickup Order,NaN,No,...,Tasting Room,CA,93446,bottlebreakage2015@lawestatewines.com,805-345-9446,805-226-9200,CA bottle processing fee,0004,NaN,NaN
freq,NaN,15,34187,25799,4506,9348,22792,27549,NaN,29736,...,2272,19361,3280,2272,2356,27582,5173,5173,NaN,NaN
mean,120480.797989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21415.706324,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.424374,2.005198e+02
std,27757.132042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17418.620583,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336.378109,1.969755e+04
min,-130912.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-12.000000,-1.080000e+03
25%,124251.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6353.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2.000000e-02
50%,126512.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10097.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,7.200000e+01
75%,129019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43775.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,1.800000e+02
max,131320.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46511.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66087.000000,3.869832e+06

In [10]:
inventory[inventory["Sale Date"].isna()]

,Order Number,Sale Date,Order Status,Fulfillment Status,Wine Club Name,Cashier,Order Source,Shipping Method,Customer No.,Pickup,...,Bill Last Name,Bill State,Bill Zip,Bill Email,Bill Phone,Ship Phone,Product Title,Part No,Qty,Net Revenue
38597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66087,3869831.55

In [11]:
inventory[inventory["Order Number"].isna()]

,Order Number,Sale Date,Order Status,Fulfillment Status,Wine Club Name,Cashier,Order Source,Shipping Method,Customer No.,Pickup,...,Bill Last Name,Bill State,Bill Zip,Bill Email,Bill Phone,Ship Phone,Product Title,Part No,Qty,Net Revenue
38597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66087,3869831.55

In [12]:
inventory[inventory["Qty"] < 0].head(20)

,Order Number,Sale Date,Order Status,Fulfillment Status,Wine Club Name,Cashier,Order Source,Shipping Method,Customer No.,Pickup,...,Bill Last Name,Bill State,Bill Zip,Bill Email,Bill Phone,Ship Phone,Product Title,Part No,Qty,Net Revenue
0,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle fee,0003,-1,-1.40
1,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle processing fee,0004,-1,-0.12
2,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2023 Audacious,AUD23,-4,-234.00
3,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2022 Sagacious,SAG22,-4,-234.00
4,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2025 Rosé,ROSE25,-3,-81.90
5,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2024 SOPH,SOPH24,-3,-175.50
6,-129083.0,2026-06-04 10:52:36.037,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,16856.0,No,...,Haisma,CA,93446,chris@inbloompasorobles.com,805-286-4344,805-226-9200,2022 Sagacious,SAG22,-6,-351.00
7,-129083.0,2026-06-04 10:52:36.037,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,16856.0,No,...,Haisma,CA,93446,chris@inbloompasorobles.com,805-286-4344,805-226-9200,2022 Audacious,AUD22,-6,-351.00
9,-122644.0,2025-11-18 14:32:24.293,NaN,NaN,NaN,Oliver Esparham,Admin Cart,UPS Ground,43534.0,No,...,Allen,CO,80523,maconallen@colostate.edu,970-491-8974,970-491-8974,2022 Audacious,AUD22,-12,-1080.00
10,-122432.0,2025-11-17 12:52:00.163,NaN,NaN,NaN,Oliver Esparham,Admin Cart,UPS Ground,43534.0,No,...,Allen,CO,80523,maconallen@colostate.edu,970-491-8974,970-491-8974,2022 Audacious,AUD22,-12,-1080.00
11,-122432.0,2025-11-17 12:52:00.163,NaN,NaN,NaN,Oliver Esparham,Admin Cart,UPS Ground,43534.0,No,...,Allen,CO,80523,maconallen@colostate.edu,970-491-8974,970-491-8974,2022 Sagacious,SAG22,-12,-1080.00
13,-122322.0,2025-11-10 14:53:01.593,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,26841.0,No,...,Thaure,CA,95140,mccloskeycarolann@gmail.com,425-208-5503,805-226-9200,"Black Label Dinner Ticket Feb 28th, 2026",0619,-2,-600.00
14,-1000.0,2025-10-09 10:38:33.550,NaN,ReadyToImport,NaN,Averi Kerr,Admin Cart,UPS Ground,18837.0,No,...,Test,CA,93446,aakerr@calpoly.edu,8052-269200,8052-269200,2022 Beguiling,BEG22,-4,0.00
15,-1000.0,2025-10-09 10:38:33.550,NaN,ReadyToImport,NaN,Averi Kerr,Admin Cart,UPS Ground,18837.0,No,...,Test,CA,93446,aakerr@calpoly.edu,8052-269200,8052-269200,2022 Aspire,ASP22,-4,0.00

In [13]:
inventory[inventory["Net Revenue"] < 0].head(20)

,Order Number,Sale Date,Order Status,Fulfillment Status,Wine Club Name,Cashier,Order Source,Shipping Method,Customer No.,Pickup,...,Bill Last Name,Bill State,Bill Zip,Bill Email,Bill Phone,Ship Phone,Product Title,Part No,Qty,Net Revenue
0,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle fee,0003,-1,-1.40
1,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,CA bottle processing fee,0004,-1,-0.12
2,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2023 Audacious,AUD23,-4,-234.00
3,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2022 Sagacious,SAG22,-4,-234.00
4,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2025 Rosé,ROSE25,-3,-81.90
5,-130912.0,2026-07-24 17:15:27.353,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,46426.0,No,...,Shorrock,CA,93446,tara.shorrock@trilogy-nevina.com,949-698-2223,805-226-9200,2024 SOPH,SOPH24,-3,-175.50
6,-129083.0,2026-06-04 10:52:36.037,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,16856.0,No,...,Haisma,CA,93446,chris@inbloompasorobles.com,805-286-4344,805-226-9200,2022 Sagacious,SAG22,-6,-351.00
7,-129083.0,2026-06-04 10:52:36.037,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,16856.0,No,...,Haisma,CA,93446,chris@inbloompasorobles.com,805-286-4344,805-226-9200,2022 Audacious,AUD22,-6,-351.00
9,-122644.0,2025-11-18 14:32:24.293,NaN,NaN,NaN,Oliver Esparham,Admin Cart,UPS Ground,43534.0,No,...,Allen,CO,80523,maconallen@colostate.edu,970-491-8974,970-491-8974,2022 Audacious,AUD22,-12,-1080.00
10,-122432.0,2025-11-17 12:52:00.163,NaN,NaN,NaN,Oliver Esparham,Admin Cart,UPS Ground,43534.0,No,...,Allen,CO,80523,maconallen@colostate.edu,970-491-8974,970-491-8974,2022 Audacious,AUD22,-12,-1080.00
11,-122432.0,2025-11-17 12:52:00.163,NaN,NaN,NaN,Oliver Esparham,Admin Cart,UPS Ground,43534.0,No,...,Allen,CO,80523,maconallen@colostate.edu,970-491-8974,970-491-8974,2022 Sagacious,SAG22,-12,-1080.00
13,-122322.0,2025-11-10 14:53:01.593,NaN,ReadyToImport,NaN,Oliver Esparham,Admin Cart,Pickup Order,26841.0,No,...,Thaure,CA,95140,mccloskeycarolann@gmail.com,425-208-5503,805-226-9200,"Black Label Dinner Ticket Feb 28th, 2026",0619,-2,-600.00

In [14]:
inventory = inventory.dropna(
    subset=["Order Number", "Sale Date"],
    how="all"
).copy()

inventory.shape

(38597, 21)

In [15]:
inventory["Sale Date"] = pd.to_datetime(
    inventory["Sale Date"],
    errors="coerce"
)

inventory["Sale Date"].dtype

dtype('<M8[ns]')

In [16]:
print(inventory["Sale Date"].min())
print(inventory["Sale Date"].max())
print("Missing dates:", inventory["Sale Date"].isna().sum())

2025-10-08 11:52:32.463000
2026-07-31 21:14:43.700000
Missing dates: 0

In [17]:
inventory["Transaction Type"] = np.where(
    (inventory["Qty"] < 0) | (inventory["Net Revenue"] < 0),
    "Return/Adjustment",
    "Sale"
)

inventory["Transaction Type"].value_counts()

Transaction Type
Sale                 38583
Return/Adjustment       14
Name: count, dtype: int64

In [18]:
negative_orders = inventory.loc[
    inventory["Order Number"] < 0,
    "Order Number"
].abs().unique()

inventory[
    inventory["Order Number"].isin(negative_orders)
][
    ["Order Number", "Sale Date", "Product Title", "Qty", "Net Revenue"]
].sort_values("Order Number")

Empty DataFrame
Columns: [Order Number, Sale Date, Product Title, Qty, Net Revenue]
Index: []

In [19]:
inventory[
    (inventory["Qty"] < 0) &
    (inventory["Net Revenue"] >= 0)
][
    ["Order Number", "Sale Date", "Product Title", "Qty", "Net Revenue"]
]

    Order Number               Sale Date   Product Title  Qty  Net Revenue
14       -1000.0 2025-10-09 10:38:33.550  2022 Beguiling   -4          0.0
15       -1000.0 2025-10-09 10:38:33.550     2022 Aspire   -4          0.0

In [20]:
inventory["Order Number"] = inventory["Order Number"].astype("Int64")
inventory["Customer No."] = inventory["Customer No."].astype("Int64")

inventory.dtypes

Order Number                   Int64
Sale Date             datetime64[ns]
Order Status                  object
Fulfillment Status            object
Wine Club Name                object
Cashier                       object
Order Source                  object
Shipping Method               object
Customer No.                   Int64
Pickup                        object
Bill First Name               object
Bill Last Name                object
Bill State                    object
Bill Zip                      object
Bill Email                    object
Bill Phone                    object
Ship Phone                    object
Product Title                 object
Part No                       object
Qty                            int64
Net Revenue                  float64
Transaction Type              object
dtype: object

In [21]:
inventory["Date"] = inventory["Sale Date"].dt.date
inventory["Month"] = inventory["Sale Date"].dt.to_period("M")
inventory["Year"] = inventory["Sale Date"].dt.year

inventory[
    ["Sale Date", "Date", "Month", "Year"]
].head()

                Sale Date        Date    Month  Year
0 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026
1 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026
2 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026
3 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026
4 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026

In [22]:
print("Order Source:")
print(inventory["Order Source"].value_counts(dropna=False))

print("\nShipping Method:")
print(inventory["Shipping Method"].value_counts(dropna=False))

print("\nWine Club Name:")
print(inventory["Wine Club Name"].value_counts(dropna=False))

Order Source:
Order Source
Point of Sale    22792
Wine Club         8550
Admin Cart        6967
Web Store          288
Name: count, dtype: int64

Shipping Method:
Shipping Method
Pickup Order       27549
UPS Ground         10634
FedEx Ground         372
UPS 2-Day             26
FedEx 2-Day           12
FedEx Overnight        4
Name: count, dtype: int64

Wine Club Name:
Wine Club Name
NaN                                              30037
Black Label (12 btls Fall, 3 btls Spring)         4506
White Label (6 bottles)                           1200
A2 Black Label (12 btls Fall, 3 btls Spring)      1136
Black Label (12 btls Fall, 6 btls Spring)          391
Consumer                                           236
Black Label (12 bottles)                           204
Black Label Allocation                             190
Black Label Dinner allocation 2026                 160
Black Label (12 btls Fall, 12 btls Spring)         159
White Label Allocation                              90
White Label Waitlist                                83
A2 Black Label (12 btls Fall, 12 btls Spring)       76
A2 White Label (6 bottles)                          75
Black Label Waitlist                                54
Name: count, dtype: int64

In [23]:
text_cols = [
    "Order Status",
    "Fulfillment Status",
    "Wine Club Name",
    "Cashier",
    "Order Source",
    "Shipping Method",
    "Bill State",
    "Product Title",
    "Part No"
]

for col in text_cols:
    inventory[col] = inventory[col].str.strip()

In [24]:
def club_group(name):
    if pd.isna(name):
        return "Non-Club"

    if "White Label Waitlist" in name:
        return "White Label Waitlist"

    if "Black Label Waitlist" in name:
        return "Black Label Waitlist"

    if "White Label Allocation" in name:
        return "White Label Allocation"

    if "Black Label Allocation" in name or "Black Label Dinner" in name:
        return "Black Label Allocation/Special"

    if "White Label" in name:
        return "White Label"

    if (
        "Black Label" in name
        and (
            "3 btls Spring" in name
            or "6 btls Spring" in name
            or "12 btls Spring" in name
        )
    ):
        return "Black Label Spring"

    if "Black Label (12 bottles)" in name:
        return "Black Label 12 Only"

    if name == "Consumer":
        return "Consumer"

    return "Other"

In [25]:
inventory["Club Group"] = inventory["Wine Club Name"].apply(club_group)

inventory["Club Group"].value_counts(dropna=False)

Club Group
Non-Club                          30037
Black Label Spring                 6268
White Label                        1275
Black Label Allocation/Special      350
Consumer                            236
Black Label 12 Only                 204
White Label Allocation               90
White Label Waitlist                 83
Black Label Waitlist                 54
Name: count, dtype: int64

In [26]:
inventory["Date"] = inventory["Sale Date"].dt.date
inventory["Month"] = inventory["Sale Date"].dt.to_period("M")
inventory["Year"] = inventory["Sale Date"].dt.year

In [27]:
inventory[
    ["Sale Date", "Date", "Month", "Year", "Wine Club Name", "Club Group"]
].head(10)

                Sale Date        Date    Month  Year Wine Club Name Club Group
0 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026            NaN   Non-Club
1 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026            NaN   Non-Club
2 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026            NaN   Non-Club
3 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026            NaN   Non-Club
4 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026            NaN   Non-Club
5 2026-07-24 17:15:27.353  2026-07-24  2026-07  2026            NaN   Non-Club
6 2026-06-04 10:52:36.037  2026-06-04  2026-06  2026            NaN   Non-Club
7 2026-06-04 10:52:36.037  2026-06-04  2026-06  2026            NaN   Non-Club
8 2025-11-18 14:27:52.790  2025-11-18  2025-11  2025            NaN   Non-Club
9 2025-11-18 14:32:24.293  2025-11-18  2025-11  2025            NaN   Non-Club

In [28]:
inventory["Club Group"].value_counts()

Club Group
Non-Club                          30037
Black Label Spring                 6268
White Label                        1275
Black Label Allocation/Special      350
Consumer                            236
Black Label 12 Only                 204
White Label Allocation               90
White Label Waitlist                 83
Black Label Waitlist                 54
Name: count, dtype: int64

In [29]:
inventory["Month Start"] = inventory["Sale Date"].dt.to_period("M").dt.to_timestamp()

inventory[
    ["Sale Date", "Month Start", "Qty", "Net Revenue"]
].head()

                Sale Date Month Start  Qty  Net Revenue
0 2026-07-24 17:15:27.353  2026-07-01   -1        -1.40
1 2026-07-24 17:15:27.353  2026-07-01   -1        -0.12
2 2026-07-24 17:15:27.353  2026-07-01   -4      -234.00
3 2026-07-24 17:15:27.353  2026-07-01   -4      -234.00
4 2026-07-24 17:15:27.353  2026-07-01   -3       -81.90

In [30]:
inventory_monthly = (
    inventory
    .groupby("Month Start")
    .agg(
        Total_Quantity=("Qty", "sum"),
        Total_Revenue=("Net Revenue", "sum"),
        Number_of_Orders=("Order Number", "nunique"),
        Number_of_Customers=("Customer No.", "nunique"),
        Number_of_Transactions=("Order Number", "size"),
        Returns_Adjustments=("Transaction Type", lambda x: (x == "Return/Adjustment").sum())
    )
    .reset_index()
)

inventory_monthly

,Month Start,Total_Quantity,Total_Revenue,Number_of_Orders,Number_of_Customers,Number_of_Transactions,Returns_Adjustments
0,2025-10-01,3141,113136.03,575,434,2083,2
1,2025-11-01,5005,321573.55,1009,764,3246,4
2,2025-12-01,3010,140787.04,529,359,1777,0
3,2026-01-01,7557,557251.16,905,708,3857,0
4,2026-02-01,18228,1331836.14,2557,2270,11014,0
5,2026-03-01,5614,238048.16,719,569,3059,0
6,2026-04-01,4946,189953.18,886,718,3127,0
7,2026-05-01,6141,270891.88,839,641,3483,0
8,2026-06-01,4641,227553.94,695,517,2714,2
9,2026-07-01,7804,478800.47,892,698,4237,6

In [31]:
inventory_monthly["Revenue_per_Order"] = (
    inventory_monthly["Total_Revenue"] /
    inventory_monthly["Number_of_Orders"]
)

inventory_monthly["Quantity_per_Order"] = (
    inventory_monthly["Total_Quantity"] /
    inventory_monthly["Number_of_Orders"]
)

inventory_monthly

,Month Start,Total_Quantity,Total_Revenue,Number_of_Orders,Number_of_Customers,Number_of_Transactions,Returns_Adjustments,Revenue_per_Order,Quantity_per_Order
0,2025-10-01,3141,113136.03,575,434,2083,2,196.758313,5.462609
1,2025-11-01,5005,321573.55,1009,764,3246,4,318.705203,4.960357
2,2025-12-01,3010,140787.04,529,359,1777,0,266.138072,5.689981
3,2026-01-01,7557,557251.16,905,708,3857,0,615.747138,8.350276
4,2026-02-01,18228,1331836.14,2557,2270,11014,0,520.858874,7.128666
5,2026-03-01,5614,238048.16,719,569,3059,0,331.082281,7.808067
6,2026-04-01,4946,189953.18,886,718,3127,0,214.394108,5.582393
7,2026-05-01,6141,270891.88,839,641,3483,0,322.874708,7.319428
8,2026-06-01,4641,227553.94,695,517,2714,2,327.415741,6.677698
9,2026-07-01,7804,478800.47,892,698,4237,6,536.771827,8.748879

In [32]:
inventory_monthly_source = (
    inventory
    .groupby(["Month Start", "Order Source"])
    .agg(
        Total_Quantity=("Qty", "sum"),
        Total_Revenue=("Net Revenue", "sum"),
        Number_of_Orders=("Order Number", "nunique")
    )
    .reset_index()
)

inventory_monthly_source.head(20)

   Month Start   Order Source  Total_Quantity  Total_Revenue  Number_of_Orders
0   2025-10-01     Admin Cart             172        6215.43                53
1   2025-10-01  Point of Sale            2969      106920.60               522
2   2025-11-01     Admin Cart             987      119309.84               260
3   2025-11-01  Point of Sale            3727      132563.71               628
4   2025-11-01      Web Store             291       69700.00               121
5   2025-12-01     Admin Cart             663       43722.20                95
6   2025-12-01  Point of Sale            2330       93224.84               426
7   2025-12-01      Web Store              17        3840.00                 8
8   2026-01-01     Admin Cart            2568      234037.69               302
9   2026-01-01  Point of Sale            2994      132735.48               449
10  2026-01-01      Web Store              26        6600.00                12
11  2026-01-01      Wine Club            1969      183877.99               142
12  2026-02-01     Admin Cart            2456      195469.93               312
13  2026-02-01  Point of Sale            3434      138960.28               487
14  2026-02-01      Wine Club           12338      997405.93              1758
15  2026-03-01     Admin Cart            1540       53701.64               112
16  2026-03-01  Point of Sale            4064      183705.88               605
17  2026-03-01      Wine Club              10         640.64                 2
18  2026-04-01     Admin Cart             649       19704.55               180
19  2026-04-01  Point of Sale            4193      165513.21               658

In [33]:
inventory.to_csv("Inventory_Cleaned.csv", index=False)
inventory_monthly.to_csv("Inventory_Monthly.csv", index=False)

In [34]:
inventory_monthly_source.to_csv(
    "Inventory_Monthly_by_Source.csv",
    index=False
)

In [35]:
print("Cleaned inventory:", inventory.shape)
print("Monthly data:", inventory_monthly.shape)
print("Monthly by source:", inventory_monthly_source.shape)

print("\nDate range:")
print(inventory["Sale Date"].min())
print(inventory["Sale Date"].max())

print("\nDuplicates:", inventory.duplicated().sum())
print("Missing dates:", inventory["Sale Date"].isna().sum())

Cleaned inventory: (38597, 27)
Monthly data: (10, 9)
Monthly by source: (31, 5)

Date range:
2025-10-08 11:52:32.463000
2026-07-31 21:14:43.700000

Duplicates: 0
Missing dates: 0